### PR TITLE
expose a config to adjust the StdBy pool size (if required)

### PR DESCRIPTION
**Pull request by venkatsridhar95**
By default, the fallback pool size is equal to the primary pool size.

### CODE REVIEW

**Review by rasamala83 — APPROVED** [review]
LGTM

**Review by shtiencode — COMMENTED** [review]
Would the minimal value better to be higher than 1? single-worker pool might potentially cause saturation features to be triggered too easily (not meaningfully helpful).

**Comment by venkatsridhar95** [comment]
@shtiencode A minimum value of 1 will be triggered only when taf_children_pct is below 0 or when the taf_children_pct of the existing worker pool size is too low.

**Comment by shtiencode** [comment]
> @shtiencode A minimum value of 1 will be triggered only when taf_children_pct is below 0 or when the taf_children_pct of the existing worker pool size is too low.

@venkatsridhar95  Yes, you could also reach 1 and it would be less meaningful. Arguably though, I can see existing readonly pct also applied same logic (with different purpose though). It looks ok to me but suggest higher default value may prevent abusive configuration.
			num = num * gAppConfig.TafChildrenPct / 100
			if num == 0 {
				num = 1

**Review by shtiencode — APPROVED** [review]
Looks good, I left a suggestion in comment for prevention of abusive setting that we can review later as issue.

**Pull request merged**
