### PR TITLE
Handle CLIENT_INFO command in worker

### PR DESCRIPTION
**Pull request by venkatsridhar95**
Helps address Issue #344 

Flag to enable/disable passing the command (EnableCmdClientInfoToWorker)

EnableCmdClientInfoToWorker enabled
``` 
// Write 
t15:43:02.07	API	CLIENT_SESSION
    E15:43:02.07	CLIENT_INFO	TestApplication	0	PoolStack=hera:CLIENT_INFO*CalThreadId=0*TopLevelTxnStartTime=18845a15936*Host=hera-host
    $1838983996	insert into mytesttable (id) values (1)
    A15:43:02.07	EXEC	1838983996	0	6.6	HOST=TESTDB
    $1838084279	insert into mytesttable (id) values (2)
    A15:43:02.18	EXEC	1838084279	0	2.6	HOST=TESTDB
    E15:43:02.29	COMMIT	Local	0
T15:43:02.30	API	CLIENT_SESSION	0	232	corr_id_=7eef73d715838&log_id_=18845a15936&worker_pid=259952&sid=769

// Read
t15:43:02.41	API	CLIENT_SESSION
    E15:43:02.41	CLIENT_INFO	TestApplication	0	PoolStack=hera:CLIENT_INFO*CalThreadId=0*TopLevelTxnStartTime=18845a15a8a*Host=hera-host
    $3523565769	select * from mytesttable
    A15:43:02.41	EXEC	3523565769	0	5.6	HOST=TESTDB
    A15:43:02.41	SQL	OCC_COLS_INFO	0	0	CMD=22
    A15:43:02.41	FETCH	3523565769	0	3.4	HOST=TESTDB&psize=28
T15:43:02.41	API	CLIENT_SESSION	0	9.6	corr_id_=7eef73d715838&log_id_=18845a15a8a&worker_pid=259924&sid=2276
```

EnableCmdClientInfoToWorker disabled 
```
// Write 
$1838983996	insert into mytesttable (id) values (1)
t15:47:48.57	API	CLIENT_SESSION
    A15:47:48.57	EXEC	1838983996	0	5.2	HOST=TESTDB
    $1838983996	insert into mytesttable (id) values (1)
    A15:47:48.67	EXEC	1838983996	0	2	HOST=TESTDB
    E15:47:48.78	COMMIT	Local	0
T15:47:48.78	API	CLIENT_SESSION	0	216	corr_id_=9fd087945b777&log_id_=18845a5b85a&worker_pid=260592&sid=769

// Read
$3523565769	select * from mytesttable
t15:47:48.91	API	CLIENT_SESSION
    A15:47:48.91	EXEC	3523565769	0	3.1	HOST=TESTDB
    A15:47:48.91	SQL	OCC_COLS_INFO	0	0	CMD=22
    A15:47:48.91	FETCH	3523565769	0	4.8	HOST=TESTDB&psize=32
T15:47:48.91	API	CLIENT_SESSION	0	8.4	corr_id_=9fd087945b777&log_id_=18845a5b9ae&worker_pid=260607&sid=1530
```

### CODE REVIEW

**Comment by shtiencode** [comment]
Would it be simpler that mux always handle CLIENT_INFO command and do CAL log but pass along the immediate client info (app name and perhaps hostname) and revise the worker to have the wanted client information to be in API payload ?

**Comment by venkatsridhar95** [comment]
@shtiencode That's exactly how it is done. When EnableCmdClientInfoToWorker is enabled, Mux handles the CLIENT_INFO command and sends the server info back to the client. Whenever the request is dispatched to the worker, it adds the client application name and the poolStack information along with the request.

**Comment by venkatsridhar95** [comment]
When EnableCmdClientInfoToWorker is enabled, Mux logs CLIENT_INFO_MUX and the worker logs CLIENT_INFO event. This is done to differentiate the two events.

**Comment by venkatsridhar95** [comment]
I will open a PR with automated tests.

**Pull request closed without merging**
